spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8088
  address: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8088
  address: 3.37.160.125


serverName: blue_server

---

spring:
    config:
      activate:
        on-profile: green

server:
    port: 8089
    address: 3.37.160.125


serverName: green_server

---

spring:
  security:
    user:
      name: user
      password: password
